### ISSUE TITLE
可否增加Kindle Text Editor?

### ISSUE THREAD

**Issue by zaoqi-unsafe** [bookfere/BookFere-Tools#4]

**Comment by bookfere** [comment]
因为这款软件不是书伴写的，所以不好加到工具包里面。这篇文章《[越狱插件 Kindle Text Editor 文本编辑器](https://bookfere.com/post/717.html) 》提供的 Kindle Text Editor 下载包含了 KUAL 菜单，解压后直接拷贝到  extionsion 文件夹中，即可在 KUAL 菜单中调用。
