### ISSUE TITLE
不存在`/usr/bin/python`导致检测安装失败

### ISSUE THREAD

**Issue by guo-yong-zhi** [bookfere/BookFere-Tools#5]
KOA2设备安装`Update_python3_0.15.N_install_pw2_kt2_kv_pw3_koa_kt3_koa2_pw4_kt4.bin`后目录为`/usr/bin/python3`。而`ht
sdr_cleaner.sh`检测`if [ ! -f /usr/bin/python3 ];`

**Comment by bookfere** [comment]
谢谢反馈，此问题已修复。
